name: mobilia
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  very_good_analysis: ^6.0.0
  connectivity_plus: ^5.0.2
  flutter_dotenv: ^5.2.1
  flutter_screenutil: ^5.9.3
  flutter_launcher_icons: ^0.14.1
  flutter_svg: ^2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - .env.dev
    - .env.prod
    - assets/svg/
    - assets/images/core/
    - assets/images/Icon_App.png

  fonts:
    - family: Avenir Arabic
      fonts:
        - asset: assets/fonts/avenir-arabic/Avenir-Regular.otf
          weight: 400
        - asset: assets/fonts/avenir-arabic/Avenir-Medium.otf
          weight: 500
        - asset: assets/fonts/avenir-arabic/AvenirArabic-Black.otf
          weight: 700

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 200
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Icon_App.png"
  adaptive_icon_background: "#7AC4A4"
  adaptive_icon_foreground: "assets/images/Icon_App.png"