name: mobilia
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.8.0
  flutter_bloc: ^8.1.6

  # very good analysis
  very_good_analysis: ^6.0.0

  # connectivity
  connectivity_plus: ^5.0.2

  # env
  flutter_dotenv: ^5.2.1

  # screen util
  flutter_screenutil: ^5.9.3

  # SVG Picture
  flutter_svg: ^2.0.16

  # Splash_screen
  flutter_native_splash: ^2.4.3

  flutter_launcher_icons: ^0.14.1
  icons_launcher: ^3.0.0

  # animation
  animate_do: ^3.3.4

  # Localization
  flutter_localization: ^0.2.2

  # Freezed 
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
# dart run build_runner build --delete-conflicting-outputs


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0 

flutter:
  uses-material-design: true

  assets:
    - .env.dev
    - .env.prod
    - assets/svg/
    - assets/images/core/
    - assets/icon/icon.png
    - assets/images/core/splash_screen/
    - assets/images/core/category/
    - assets/images/core/home page banner/
    - assets/images/core/pages/
    - assets/images/core/products/
    - assets/images/core/sofa icon.png
    - assets/icon/day-and-night.png
    - assets/icon/globe.png


  fonts:
    - family: Avenir Arabic
      fonts:
        - asset: assets/fonts/avenir/Avenir-Regular.otf
          weight: 400
        - asset: assets/fonts/avenir/Avenir-Medium.otf
          weight: 500
        - asset: assets/fonts/avenir/AvenirArabic-Black.otf
          weight: 700

    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 200
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
    - family: Italiana
      fonts:
        - asset: assets/fonts/italiana/Italiana-Regular.ttf
          weight: 500

flutter_native_splash:
  color: "#7AC4A4"
  image: assets/images/core/splash_screen/Splash_ icon.png
  android_12:
    color: "#7AC4A4"
    image: assets/images/core/splash_screen/Splash_ icon_12.png

